graph TD

  subgraph Loader [Automation Loader]
    AutomationLoader[AutomationLoader.py]
  end

  subgraph Constants Files [Constants Modules]
    TextCreatorConstants[TextCreatorConstants]
  end

  subgraph Tool Configs [Tool Config Files]
    TextCreatorConfig[TextCreator.json]
  end

  AutomationLoader --> TextCreatorConstants
  TextCreatorConstants --> TextCreatorConfig
  class AutomationLoader primary
  class TextCreatorConstants secondary
  class TextCreatorConfig tertiary