graph TD

  subgraph Loader [Testing Tools Loader]
    ToolLoader[ToolLoader.py]
  end

  subgraph Constants Files [Constants Modules]
    WiFiConstants[WiFiConstants]
    NetworkConstants[NetworkConstants]
  end

  subgraph Tool Configs [Tool Config Files]
    WiFiConfig[WiFiConfig.json]
    NetworkConfig[NetworkConfig.json]
  end

  ToolLoader --> WiFiConstants
  ToolLoader --> NetworkConstants
  WiFiConstants --> WiFiConfig
  NetworkConstants --> NetworkConfig
  class ToolLoader primary
  class WiFiConstants secondary
  class NetworkConstants secondary
  class WiFiConfig tertiary
  class NetworkConfig tertiary