graph TD

  subgraph Data Exploration [Data Exploration]
    ThematicAnalysis[Thematic Analysis]
  end

  subgraph Factor Analysis [Factor Analysis]
    Glossary[Glossary]
    SearchTool[Search Tool]
  end

  subgraph Entities [Entities]
    factorG[Factor]
    factorS[Factor]
    group[Group]
    sub_group[Sub Group]
    category[Category]
    sub_category[Sub Category]
  end

  ThematicAnalysis --> Glossary
  ThematicAnalysis --> SearchTool
  Glossary --> factorG
  Glossary --> group
  Glossary --> sub_group
  SearchTool --> factorS
  SearchTool --> category
  SearchTool --> sub_category
  class ThematicAnalysis primary
  class Glossary secondary
  class SearchTool secondary
  class factorG tertiary
  class group tertiary
  class sub_group tertiary
  class factorS tertiary
  class category tertiary
  class sub_category tertiary