@startuml
title Thematic Analysis ERD
hide stereotype
hide circle
skinparam BackgroundColor #ffffff
skinparam ClassBackgroundColor #dab3ff
skinparam ClassBorderColor #4b0082
skinparam ClassFontColor #000000
skinparam ClassFontStyle bold
skinparam ClassAttributeIconSize 0
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam ArrowColor #0000ff
skinparam ArrowFontColor #000000
skinparam ArrowThickness 2
skinparam LineColor #0000ff
skinparam LineThickness 2
skinparam linetype ortho
skinparam roundcorner 15
skinparam shadowing false
' --- entities ---
class "Thematic Analysis" as ThematicAnalysis {
  ID
  Extract
  Fact
  Factor
  Note
}

class "Glossary" as Glossary {
  Factor
  Group
  Sub Group
}

class "Search Tool" as SearchTool {
  Factor
  Catergory
  Sub Category
  Extract
}

' --- relationships ---
ThematicAnalysis ||-down-o{ Glossary
ThematicAnalysis ||-down-o{ SearchTool
Glossary -[hidden]right- SearchTool
ThematicAnalysis -[hidden]down- Glossary
ThematicAnalysis -[hidden]down- SearchTool
@enduml