graph TD

  subgraph Main + Selector [Main Script & Model Selector]
    MainScripts[Main Scripts]
    AppConfig[AppConfig]
  end

  subgraph Device Models [Device Models]
    Desktop[Desktop]
    MediaCentre[MediaCentre]
    Laptop[Laptop]
  end

  subgraph Config Files [Configuration Files]
    DesktopJSON[Desktop.json]
    MediaCentreJSON[MediaCentre.json]
    LaptopJSON[Laptop.json]
  end

  MainScripts --> AppConfig
  AppConfig --> Desktop
  AppConfig --> MediaCentre
  AppConfig --> Laptop
  Desktop --> DesktopJSON
  MediaCentre --> MediaCentreJSON
  Laptop --> LaptopJSON
  class MainScripts primary
  class AppConfig primary
  class Desktop secondary
  class MediaCentre secondary
  class Laptop secondary
  class DesktopJSON tertiary
  class MediaCentreJSON tertiary
  class LaptopJSON tertiary