graph TD

  subgraph HTMLPages [HTML Pages]
    Index[Index.html]
    Module[module.html]
  end

  subgraph JavaScript [JavaScript]
    Controller[Controller.js]
    Question[Question.js]
    Quiz[Quiz.js]
    InitModuleList[initModuleList.js]
    InitQuizPage[initQuizPage.js]
    InitResultsPage[initResultsPage.js]
  end

  subgraph JSONData [JSON Data]
    QuizDataJSON[QuizData-JSON.js]
  end

  Index --> Module
  Module --> Controller
  Module --> Question
  Module --> Quiz
  Module --> InitModuleList
  Module --> InitQuizPage
  Module --> InitResultsPage
  Controller --> QuizDataJSON
  Question --> QuizDataJSON
  Quiz --> QuizDataJSON
  InitModuleList --> QuizDataJSON
  InitQuizPage --> QuizDataJSON
  InitResultsPage --> QuizDataJSON
  class Index primary
  class Module primary
  class Controller secondary
  class Question secondary
  class Quiz secondary
  class InitModuleList secondary
  class InitQuizPage secondary
  class InitResultsPage secondary
  class QuizDataJSON tertiary