graph TD

  subgraph HTMLPages [HTML Pages]
    Index[Index.html]
  end

  subgraph JavaScript [JavaScript]
    initSearchTool[initSearchTool.js]
    SearchTool[SearchTool.js]
  end

  subgraph JSONData [JSON Data]
    toolJSON[toolJSON.js]
  end

  Index --> initSearchTool
  Index --> SearchTool
  initSearchTool --> toolJSON
  SearchTool --> toolJSON
  class Index primary
  class initSearchTool secondary
  class SearchTool secondary
  class toolJSON tertiary